language: node_js
node_js: 
  - 10

env:
  - AWS_REGION="us-east-1"
  - AWS_ACCESS_KEY_ID="secrethub://company/app/aws/access_key_id"
  - AWS_SECRET_ACCESS_KEY="secrethub://company/app/aws/secret_access_key"

before_install:
- pyenv global 3.7.1
- pip install -U pip
- pip install awscli


before_script:
- wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
- yarn install

script:
- npm rebuild node-sass
- yarn prod-build
- hugo --minify
- yarn sass-compile

deploy:
  provider: s3
  access_key_id: AKIAIN5O72B44O5TWFVA
  secret_access_key:
    secure: ofq2WdkVFtijG9rfv4iXTGKsiPoaX1hRLxWExB3Pj8FK9dm10IqqeRbR042IKgd260HmtazVmsQ/BgQASY1QDZwmugC1WMSPx3WUxEwtOmI2Il1SL4yqz5GGJ9fCu3yJ9Y668Foh178Q10rd6C6qMUuhFASUPIo4ujXOdCZmN4rzwq7GK9XgRbdNvNSgXmuUbSPI5zhnVvShJJDtJgR+VCh5QXdb8Vokb0BxnaooRgHgh7JtjgT7hs31TAXZ8LmmJfXc7XFePKt8WShbNa2O2M8vyE7sFwRsMiGTNTYLO/5wo0QT/1l1Q6CdDjyiS3DUOldS1y2mbOaAgSvL9oCemMx2UYD4ucPXNekeFRrKI86jBEjKGFnOspqL8Cx5us7181JxBZW1zVoj7p2tsfzQXnvkZ7SUQ86+99sPxA4kejWl5Wlfli2aBVjx9jCxC0UO7ii97FXbPDQKSAIEk/LyRc1Rh1EKeaHt0BK+6+WNeuQNtbF+hlFDXIKX6Gsly61hZpZF1Sdt/oFehVO5hHB+jPEL4IYGt8N2rsoSoJtzVsH2lafxsFZrS0/rf4n/iAmw/hK0NJ+S1U/5YfjfEQopWBN3mUv9ACzFeSkDT6FUHkWAwbuqJSEuXiuHY3gU6UmLWK+GkQKWxfM2lnQbOJDczg0KScOi1/O8qLJrcNV1RzE=
  bucket: tutorialedge.net
  local-dir: public
  skip_cleanup: true
  region: eu-west-1
  acl: public_read
  on:
    repo: elliotforbes/tutorialedge.net
    branch: master

after_script:
- export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
- export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
- export REGION=eu-west-1
- aws cloudfront create-invalidation --distribution-id E2USZE9G60PEM6 --paths "*"