---
apiVersion: v1
kind: Service
metadata:
  name: tutorialedge-rest-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    name: tutorialedge-rest-api