name: Production Deploy

on:
  push:
    branches:
      - content

jobs:
  #----------------------------------
  # Build job performs the action of building and testing
  # the site
  #----------------------------------
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    

      - name: Install NPM 
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.72.0'
          
      - name: Build
        run: |
          echo "Building Site"
          npm install
          npm run prod-build
          hugo --minify
          npm run sass-compile

  #----------------------------------
  # Deploy job performs the action of deploying the
  # built artefacts to the S3 bucket that hosts
  # tutorialedge
  #----------------------------------
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Deploy
        run: |
          echo "Deploying Site"
          ls public
      