name: Broken Link Checker

on:
  push:
    branches:
      - content

jobs:
  #----------------------------------
  # Validation Jobs for the site
  #----------------------------------
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Check for broken links
      id: link-report
      uses: elliotforbes/broken-link-checker@0.1
      with:
        url: 'https://tutorialedge.net'
    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"